### ISSUE TITLE
NestedScrollView

### ISSUE THREAD

**Issue by iambudi** [MSzalek-Mobile/weight_tracker#23]
Hi, Thanks for your article https://marcinszalek.pl/flutter/flutter-tabbar-example-weighttracker-5/ Showing/Hiding App bar title when scrolling content works flawlessly when the content is on the first page, when its in the middle of long content, showing/hiding title seems to be delay. 

Any clue to solve it?

Here's the screenshoot http://sendvid.com/37jr6ige

**Comment by MarcinusX** [comment]
Hi!
I've never seen it before.
I will try to take a look at this week :)

**Comment by MarcinusX** [comment]
Or if you solve it before me, please share your solution here or by pull request :)

**Comment by iambudi** [comment]
Hi, 
Well i have not found solution to that at the moment :)
I learn by reading from your code, just few weeks knowing flutter so still need a lot to learn :)

**Comment by MarcinusX** [comment]
I don't think it's happening in the app, so I'm closing issue for now.
